server:
  port: ${PORT:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.dsalathe.dev/realms/dsalathe-apps

app:
  keycloak:
    client-id: tchutchu
