spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

application:
  name: "tchutchu"
  description: "An implementation of the game Tickets to ride in scala 3, with WebSockets"

app:
  keycloak:
    client-id: tchutchu

server:
  port: ${PORT:8080}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always

logging:
  file:
    name: logs/tchutchu.log
