package ch.coachdave.tchutchu.game

enum UserAction:
  case JOINING_GAME, INITIAL_TICKETS_CHOSEN, PLAY_TURN, FIRST_CARD, CLAIMING_ROUTE, ASK_MORE_TICKETS, DRAW_SECOND, ADDITIONAL_CARDS_CHOSEN, ADDITIONAL_TICKETS_CHOSEN, DISTRIBUTING_INITIAL_TICKETS, NOTHING
